base: 'http://online-scrap-project.ddev.site/'
baseVariants:
  -
    base: 'http://online-scrap-project.ddev.site/'
    condition: 'getenv("DDEV_PROJECT") == "online-scrap-project"'
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    flag: en-us-gb
    languageId: '0'
rootPageId: 1
routes: {  }

